### ISSUE TITLE
Lien non fonctionnel

### ISSUE THREAD

**Issue by JulianGabinAtienza** [Anas7823/Portfolio-EL-KHIAT-Anas#1]
Le lien vers le dépôt GitHub "ThyDev" dans la section "Projets" ne fonctionne pas et renvoie une erreur 404.

**Comment by Anas7823** [comment]
Bonjour, je vous remercie pour votre retour.
Pouvez vous m'envoyer le lien vers le quel vous êtes rediriger afin que je puisse comparer ma redirection et la votre ?

Cordialement,
EL KHIAT Anas

**Comment by Anas7823** [comment]
Après vérification, j'ai remarqué que le repo est privé, c'est donc pour ça que le résultat renvoyer est 404.
Selon le contenue du repo, je le mettrai en public ou supprimerais la redirection sur mon portfolio

Merci pour votre retour
